openapi: 3.0.3
info:
  title: GinTuto
  description: GinTuto
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /images:
    get:
      description: Get a list of images as JSON
      responses:
        '200':
          description: Get the list of images as JSON
    post:
      description: Create a new image
      responses:
        '201':
          description: Image created
  /images/{id}:
    get:
      description: Download an image with its ID
      responses:
        '200':
          description: Download successful